# Project
project: Jumpgate
lead: "A simple library to make more clouds compatible with OpenStack"
public_url: http://softlayer.github.io/jumpgate

# GitHub
repo: http://github.com/softlayer/jumpgate
fork: http://github.com/softlayer/jumpgate/fork
star: http://github.com/softlayer/jumpgate/stargazers
open_issues: http://github.com/softlayer/jumpgate/issues?milestone=1;state=open
closed_issues: http://github.com/softlayer/jumpgate/issues?milestone=1;state=closed
milestones: http://github.com/softlayer/jumpgate/issues/milestones?state=open
commits: http://github.com/softlayer/jumpgate/commits
contributors: https://github.com/softlayer/jumpgate/graphs/contributors
license: https://raw.github.com/softlayer/jumpgate/master/LICENSE

# Company
www: http://www.softlayer.com
sldn: http://sldn.softlayer.com
kb: http://knowledgelayer.softlayer.com
blog: http://blog.softlayer.com

# Social
github: http://github.com/softlayer
twitter: http://twitter.com/softlayerdevs

# Server
permalink: pretty
exclude: [".gitignore", "README.md", "LICENSE", "template"]
pygments: true
safe: false

# Google Analytics
ga_tracking_id: UA-40037365-2
ga_tracking_domain: softlayer.github.io